# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal }:

cabal.mkDerivation (self: {
  pname = "acl2";
  version = "0.0.1";
  sha256 = "0bwlsdxk3lbir90xhar7xd83cwarqcm0a86gvwaghknpil2ay4cg";
  meta = {
    description = "Writing and calling ACL2 from Haskell";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
