# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, dataTextual, parsers, tagged, textPrinter
, transformersBase
}:

cabal.mkDerivation (self: {
  pname = "data-timeout";
  version = "0.3";
  sha256 = "1b6af2x19hb1kynsv7ypc2q6b71cazcg86gf1yhq0rr0fjj478ah";
  buildDepends = [
    dataTextual parsers tagged textPrinter transformersBase
  ];
  meta = {
    homepage = "https://github.com/mvv/data-timeout";
    description = "64-bit timeouts of nanosecond precision";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
