# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, fetchgit, ghcPaths, syb, makeWrapper, ncurses, ghc }:

cabal.mkDerivation (self: {
  pname = "ghci-ng";
  version = "7.8.3";
  src = fetchgit {
    url = "git://github.com/chrisdone/ghci-ng.git";
    sha256 = "0f56dfa655a4d3072727fe91d1faa331f0c1aaea9ce8561ce180d7dcc39d005e";
    rev = "2f8c2b158a61d4098e923544247f28238dfbbc66";
  };
  buildDepends = [ ghcPaths syb ];
  buildTools = [ makeWrapper ncurses ];
  postInstall = ''
    wrapProgram $out/bin/ghci-ng --add-flags "-package ghc \$(${ghc.GHCGetPackages} ${ghc.version} \"\$(dirname \$0)\")"
  '';
  isLibrary = false;
  isExecutable = true;
  meta = {
    homepage = "https://github.com/chrisdone/ghci-ng";
    description = "Next generation GHCi";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
