# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ mkDerivation, fetchFromGitHub, ghc-paths, syb, makeWrapper, ncurses, ghc }:

mkDerivation {
  pname = "ghci-ng";
  version = "20141206";
  src = ../Source/ghci-ng;
  # src = fetchFromGitHub {
  #   owner = "chrisdone";
  #   repo = self.pname;
  #   rev = "3e58908923d590815b617149beb36236d64f7392";
  #   sha256 = "0nv2v4flqb28injqmvgm12vmpmm6l26qa74d5yfdhhyzijwijpga";
  # };
  buildDepends = [ ghc-paths syb ];
  buildTools = [ makeWrapper ncurses ];
  isLibrary = false;
  isExecutable = true;
}
