# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, fetchFromGitHub, ghcPaths, syb, makeWrapper, ncurses, ghc }:

cabal.mkDerivation (self: {
  pname = "ghci-ng";
  version = "20141206";
  src = ../Source/ghci-ng;
  # src = fetchFromGitHub {
  #   owner = "chrisdone";
  #   repo = self.pname;
  #   rev = "3e58908923d590815b617149beb36236d64f7392";
  #   sha256 = "0nv2v4flqb28injqmvgm12vmpmm6l26qa74d5yfdhhyzijwijpga";
  # };
  buildDepends = [ ghcPaths syb ];
  buildTools = [ makeWrapper ncurses ];
  postInstall = ''
    wrapProgram $out/bin/ghci-ng --add-flags "-package ghc \$(${ghc.GHCGetPackages} ${ghc.version} \"\$(dirname \$0)\")"
  '';
  isLibrary = false;
  isExecutable = true;
  meta = {
    homepage = "https://github.com/chrisdone/ghci-ng";
    description = "Next generation GHCi";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
