# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, alex, exceptionMtl, exceptionTransformers, fetchgit
, filepath, happy, haskellSrcMeta, HUnit, mainlandPretty, mtl
, srcloc, syb, symbol, testFramework, testFrameworkHunit
}:

cabal.mkDerivation (self: {
  pname = "language-c-quote";
  version = "0.10.1.1";
  sha256 = "1aklnd85dxskbbv8kwjfr2izsm11x633rg2wpkq3a7cx93w3zpls";
  doCheck = false;
  buildDepends = [
    exceptionMtl exceptionTransformers filepath haskellSrcMeta
    mainlandPretty mtl srcloc syb symbol
  ];
  testDepends = [
    HUnit srcloc symbol testFramework testFrameworkHunit
  ];
  buildTools = [ alex happy ];
  meta = {
    homepage = "http://www.cs.drexel.edu/~mainland/";
    description = "C/CUDA/OpenCL/Objective-C quasiquoting library";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
