# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, alex, exceptionMtl, exceptionTransformers, fetchgit
, filepath, happy, haskellSrcMeta, HUnit, mainlandPretty, mtl
, srcloc, syb, symbol, testFramework, testFrameworkHunit
}:

cabal.mkDerivation (self: {
  pname = "language-c-quote";
  version = "0.8.1";
  src = fetchgit {
    url = "git://github.com/pchickey/language-c-quote.git";
    sha256 = "320c8cfb82b9547cb0dd37f3ed0cd9b5db4bd3d734ace7be844138ef78a383f6";
    rev = "20b2032c0765f9c4bad08af6fd388d45b65c2537";
  };
  buildDepends = [
    exceptionMtl exceptionTransformers filepath haskellSrcMeta
    mainlandPretty mtl srcloc syb symbol
  ];
  testDepends = [
    HUnit srcloc symbol testFramework testFrameworkHunit
  ];
  buildTools = [ alex happy ];
  meta = {
    homepage = "http://www.cs.drexel.edu/~mainland/";
    description = "C/CUDA/OpenCL/Objective-C quasiquoting library";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
