# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal }:

cabal.mkDerivation (self: {
  pname = "simple-smt";
  version = "0.3.0";
  sha256 = "0mvpl8wgqdjsmxaqpkvmabvagpripfasp1ad9cy5z17j5fh57fpd";
  meta = {
    description = "A simple way to interact with an SMT solver process";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
