# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, caseInsensitive, dataChecked, hashable, text }:

cabal.mkDerivation (self: {
  pname = "text-latin1";
  version = "0.3";
  sha256 = "1cs09qwkcljbnckakzr1wnpclkzjb0in3nnz6fpjyl4mxp5bqaw9";
  buildDepends = [ caseInsensitive dataChecked hashable text ];
  meta = {
    homepage = "https://github.com/mvv/text-latin1";
    description = "Latin-1 (including ASCII) utility functions";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
