# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, QuickCheck, semigroups, testFramework
, testFrameworkQuickcheck2, text, textLatin1
}:

cabal.mkDerivation (self: {
  pname = "text-printer";
  version = "0.4";
  sha256 = "0jcixgxln4c12nzmj50g3mmslki6f083xjrm9hr6hqvqzffxny5q";
  buildDepends = [ semigroups text textLatin1 ];
  testDepends = [
    QuickCheck testFramework testFrameworkQuickcheck2
  ];
  meta = {
    homepage = "https://github.com/mvv/text-printer";
    description = "Abstract interface for text builders/printers";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
