# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, tagged }:

cabal.mkDerivation (self: {
  pname = "type-hint";
  version = "0.1";
  sha256 = "1fcrma7m6y7i1y42rzhv7qch8xkk93lkh1767saw4hsb9fzwsq8i";
  buildDepends = [ tagged ];
  meta = {
    homepage = "https://github.com/mvv/type-hint";
    description = "Guide type inference with proxy values";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
